### ISSUE TITLE
Infografia Actividad 4

### ISSUE THREAD

**Issue by 22620229Angel** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-22620229Angel#1]
[Infografia Librerias.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-22620229Angel/files/14529681/Infografia.Librerias.pdf)

**Comment by ElisabetRD** [comment]
19% falta ilustraciones y créditos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
